### ISSUE TITLE
gitops-v2: dockerLint ignoreRuleViolations set to false causes error

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/azure-devops-templates#62]
```
Job image: Step specifies condition and(succeeded(), eq(, true), eq(variables['Build.sourceBranch'], 'refs/heads/master')) which is not valid. Reason: Unexpected symbol: ','. Located at position 21 within expression: and(succeeded(), eq(, true), eq(variables['Build.sourceBranch'], 'refs/heads/master')).
```

**Comment by Sundin** [comment]
👀

**Comment by simongottschlag** [comment]
@Sundin I'm back from the vacation next week and will create a PR for it 👍

**Comment by simongottschlag** [comment]
@Sundin I've been looking at this now and I actually think this is "by design" from Azure DevOps.

The parameter looks like this:

```yaml
  - name: dockerLint
    type: object
    default:
      enable: true
      ignoreRuleViolations: true
```

If you configure the following, it will fail due to `enable` not being a parameter of `docklerLint`:

```yaml
stages:
  - template: gitops-v2/build/main.yaml@templates
    parameters:
      poolName: "xks-vmss"
      sourceBranch: "refs/heads/main"
      serviceName: "service"
      dockerfilePath: "./.ci/Dockerfile"
      dockerLint:
        ignoreRuleViolations: false
```

If you add the parameter `enable` to `dockerLint`, it should work:

```yaml
stages:
  - template: gitops-v2/build/main.yaml@templates
    parameters:
      poolName: "xks-vmss"
      sourceBranch: "refs/heads/main"
      serviceName: "service"
      dockerfilePath: "./.ci/Dockerfile"
      dockerLint:
        enable: true
        ignoreRuleViolations: false
```
